# Warning control
import os
import yaml
import warnings
#import agentops
from crewai.project import CrewBase

warnings.filterwarnings('ignore')

from dotenv import load_dotenv, find_dotenv
from crewai import Agent, Process, Task, Crew, LLM
from crewai.project import CrewBase, agent, crew, task, llm

from crewai_tools import DallETool
load_dotenv()
os.environ["OPENAI_MODEL_NAME"] = 'gpt-4o-mini'

from pydantic import BaseModel, Field
from typing import List
from langchain_openai import ChatOpenAI

dalle_tool = DallETool(model="dall-e-3",
                       size="1024x1024",
                       quality="standard",
                       n=1)


# Define a class for an individual scene
class StoryScene(BaseModel):
    scene_number: int
    narration: str


# Define a class for a list of story scenes
class StoryScenes(BaseModel):
    story_name: str
    summary: str
    background: str
    lesson: str
    scenes: List[StoryScene]


# Define a class for an individual scene
class SceneImage(BaseModel):
    prompt: str = Field(description="A prompt for text to image models that can be used to generate an image.",
                        max_length=50)
    image_url: str = Field(description="Url to the image generated by the tool")


@CrewBase
class StoryCrew():
    """StoryCrew crew"""

    agents_config = 'ComicBookConfig/StoryAgents.yaml'
    tasks_config = 'ComicBookConfig/StoryTasks.yaml'

    @llm
    def llm_model(self):
        return ChatOpenAI(temperature=0.0,  # Set to 0 for deterministic output
                          model="gpt-4o-mini")

    @agent
    def scriptwriter(self) -> Agent:
        return Agent(
            config=self.agents_config['scriptwriter'],
            output_pydantic=StoryScenes,
            verbose=True
        )

    @task
    def scriptwriting(self) -> Task:
        return Task(
            config=self.tasks_config['scriptwriting'],
            output_pydantic=StoryScenes,
        )

    @crew
    def crew(self) -> Crew:
        """Creates the StoryCrew crew"""
        script_crew = Crew(
            agents=self.agents,  # Automatically created by the @agent decorator
            tasks=self.tasks,  # Automatically created by the @task decorator
            process=Process.sequential,
            verbose=True,
            manager_llm = ChatOpenAI(temperature=0.0, model="gpt-4o-mini")  # Using the GPT-4 Turbo model

            # process=Process.hierarchical, # In case you wanna use that instead https://docs.crewai.com/how-to/Hierarchical/
        )

        return script_crew


@CrewBase
class ArtistCrew():
    agents_config = 'ComicBookConfig/VisualAgents.yaml'
    tasks_config = 'ComicBookConfig/VisualTasks.yaml'

    @llm
    def llm_model(self):
        return ChatOpenAI(temperature=0.0,  # Set to 0 for deterministic output
                          model="gpt-4o-mini")

    @agent
    def visualartist(self) -> Agent:
        return Agent(
            config=self.agents_config['visualartist'],
            tools=[dalle_tool],
            verbose=True
        )

    @task
    def illustration(self) -> Task:
        return Task(
            config=self.tasks_config['illustration'],
            output_pydantic=SceneImage,

            output_file='report.md'
        )

    @crew
    def crew(self) -> Crew:
        """Create the picture book crew"""
        artist_crew = Crew(
            agents=self.agents,  # Automatically created by the @agent decorator
            tasks=self.tasks,  # Automatically created by the @task decorator
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, # In case you wanna use that instead https://docs.crewai.com/how-to/Hierarchical/
        )

        return artist_crew

#agentops.init(os.environ.get("AGENTOPS_API_KEY"))
#agentops.start_session( tags = ['story', 'scripts'] )

number_of_scenes = 3
story_text = "Once upon a time, there lived a mighty lion named Bhasuraka, who terrorized the jungle. The animals, tired of his tyranny, decided to send him a prey every day. One day, it was a clever rabbit’s turn, and he devised a plan to rid the jungle of the lion. He led Bhasuraka to a deep well, convincing him that another lion lived there. Bhasuraka, seeing his reflection in the water, roared in anger and jumped into the well, never to return."
# Creating hypothesis or generating questions using QuestCrew
inputs = {
    'number_of_scenes': int(number_of_scenes),
    'story_text': story_text,
}

scenes_list = StoryCrew().crew().kickoff(inputs=inputs)

#agentops.end_session("Success")

if scenes_list is not None:
    print(f"Raw result from script writing: {scenes_list.raw}")

slist = scenes_list.pydantic
story_summary = slist.summary
for scene in slist.scenes:
    print(f"Scene: {scene.narration}")

scene_input = [{ "story_summary": story_summary,
    'scene_description': scene.narration} for i, scene in enumerate(slist.scenes)]

#agentops.start_session(tags = ['scene', 'illustration'])

# Run the agent
result_images = ArtistCrew().crew().kickoff_for_each(inputs = scene_input)

print("result_images : {result_images.raw}")